name: has_bogor
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '^3.4.0' 
flutter:
  assets:
    - assets/images/

  uses-material-design: true

# Dependencies section
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  pbp_django_auth: ^0.3.1
  animated_text_kit: ^4.2.1 
  intl: ^0.18.0

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
